### ISSUE TITLE
Basic/Command 似乎存在问题

### ISSUE THREAD

**Issue by whocansee** [X1r0z/JNDIMap#4]
测试版本：JDK8u66、JDK8u121，Windows，不能执行命令

**Comment by Carnival-z** [comment]
//发现有时候调用scriptenjen再执行会出现报错
    @JNDIMapping("/{cmd}")
    public byte[] UnscriptCommand(String cmd) throws Exception {
        byte[] byteArray = cmd.getBytes();
        return byteArray;
    }

**Comment by Carnival-z** [comment]
不好意思 我的问题 没有描述清晰 jdk 11.22 中 测试发现报错 Forced String setter eval threw exception for property x 
![image](https://github.com/X1r0z/JNDIMap/assets/59604995/97fa3ea3-d8e7-4287-b968-d072e961f850)
问题可能是 通过code 通过javascirpt eng 执行可能会出错 
![image](https://github.com/X1r0z/JNDIMap/assets/59604995/c6651754-b925-49ae-9ad1-b05e2c2ea146)
yuan'sheng原生的似乎ok

**Comment by X1r0z** [comment]
> 不好意思 我的问题 没有描述清晰 jdk 11.22 中 测试发现报错 Forced String setter eval threw exception for property x 
> 
> ![image](https://github.com/X1r0z/JNDIMap/assets/59604995/97fa3ea3-d8e7-4287-b968-d072e961f850)
> 
> 问题可能是 通过code 通过javascirpt eng 执行可能会出错 
> 
> ![image](https://github.com/X1r0z/JNDIMap/assets/59604995/c6651754-b925-49ae-9ad1-b05e2c2ea146)
> 
> yuan'sheng原生的似乎ok

高版本 tomcat 用不了 TomcatBypass 这个功能, 因为被修复了
Tomcat 8 系列的版本必须满足 < 8.5.79

https://github.com/apache/tomcat/commit/48dd609fd193dbe8dd94fd231c45d987da6c359f

Tomcat 9, 10 等大版本也有类似的修复 commit, 晚些时间我会把版本号补充进 README.md

**Comment by Carnival-z** [comment]
我测试发现 jdk确实很关键 jdk-11.0.22  中不能使用 nashorn  。。。。
![image](https://github.com/X1r0z/JNDIMap/assets/59604995/e0a3f1e3-d55e-4b37-a2e6-cf6b898bb8b0)
```
Warning: Nashorn engine is planned to be removed from a future JDK release
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to module jdk.scripting.nashorn.scripts
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$7$\^eval\_$cu1$restOf.:program(<eval>:1)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at test.A1.main(A1.java:23)

```

**Comment by X1r0z** [comment]
看了下, 需要绕过高版本 JDK 反射的限制, 或者直接反射调用 Unsafe.defineAnonymousClass, 可以先参考:
https://github.com/yzddmr6/Java-Js-Engine-Payloads
https://github.com/knownsec/KCon/blob/master/2021/%E9%AB%98%E7%BA%A7%E6%94%BB%E9%98%B2%E6%BC%94%E7%BB%83%E4%B8%8B%E7%9A%84Webshell.pdf

我这边期末周了, 晚点会修复
